services:

  hello-world:
    image: hello-world:${IMAGE_TAG:?IMAGE_TAG must be set}
    container_name: hello-world
    restart: unless-stopped
    build:
      context: ./hello-world
      dockerfile: Dockerfile
    ports:
      - "4200:8080"

  hello-world-rpt:
    image: hello-world-rpt:${IMAGE_TAG:?IMAGE_TAG must be set}
    container_name: hello-world-rpt
    restart: unless-stopped
    build:
      context: ./hello-world-rpt
      dockerfile: Dockerfile
    ports:
      - "5200:8080"

      services:

  postgres:
    image: postgres:18
    container_name: enterprise-postgres
    environment:
      POSTGRES_DB: paysprint
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "$DB_PORT:$DB_PORT"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d enterprise"]
      interval: 2s
      timeout: 5s
      retries: 15
