services:

  hello-world:
    image: hello-world:${IMAGE_TAG:?IMAGE_TAG must be set}
    container_name: hello-world
    restart: unless-stopped
    build:
      context: ./hello-world
      dockerfile: Dockerfile
    ports:
      - "4200:8080"
