sonar.projectKey=hello-world-app
sonar.projectName=Hello World Application

sonar.sources=.

sonar.exclusions=\
**/node_modules/**,\
**/target/**,\
**/dist/**,\
**/.venv/**,\
**/venv/**,\
**/__pycache__/**

# Java
sonar.coverage.jacoco.xmlReportPaths=\
java-service/target/site/jacoco/jacoco.xml

# Python
sonar.python.coverage.reportPaths=\
holdings-service/coverage.xml,\
market-service/coverage.xml

# Angular / TypeScript
sonar.javascript.lcov.reportPaths=\
angular-app/coverage/lcov.info
