spring.application.name=mission-service

spring.datasource.url=jdbc:postgresql://localhost:5432/leapdb
spring.datasource.username=brianhickey
spring.datasource.password=ROmans23&

mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

jwt.shared-secret=mission-control-shared-secret-key-32-bytes-minimum

server.port=8090
